/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servis_otomasyonu;

import java.sql.Time;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HONOR
 */
public class OkulEkran extends javax.swing.JDialog {
 Servis_otomasyonu islemler = new Servis_otomasyonu();
    DefaultTableModel model;
    public OkulEkran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
           model = (DefaultTableModel) okulTable.getModel();
        okulGoruntule();
        durumKontrol(true);
    }
     public void okulGoruntule() {
        model.setRowCount(0);
        ArrayList<okulClass> okul = new ArrayList<>();
        okul = islemler.okulGetir();
        if (okul != null) {
            for (okulClass Okul : okul) {
                Object[] eklenecek = {Okul.getOkulID(),Okul.getOkulAdi(),Okul.getAdres(),Okul.getBaslamaSaati(),Okul.getBitisSaati()};
                model.addRow(eklenecek);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOkulAdi = new javax.swing.JTextField();
        txtSaat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOkulAdres = new javax.swing.JTextArea();
        btnOkulEkle = new javax.swing.JButton();
        btnOkulSil = new javax.swing.JButton();
        btnOkulDuzenle = new javax.swing.JButton();
        lblMesaj = new javax.swing.JLabel();
        btnTemizle = new javax.swing.JButton();
        lblArama = new javax.swing.JLabel();
        txtArama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBitisSaati = new javax.swing.JTextField();
        btnYeni = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        okulTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Okul Adı");

        jLabel3.setText("Okul Başlama Saati");

        jLabel7.setText("Okul Adres");

        txtOkulAdi.setEnabled(false);

        txtSaat.setEnabled(false);

        txtOkulAdres.setColumns(20);
        txtOkulAdres.setRows(5);
        txtOkulAdres.setEnabled(false);
        jScrollPane2.setViewportView(txtOkulAdres);

        btnOkulEkle.setBackground(new java.awt.Color(153, 153, 153));
        btnOkulEkle.setText("Okul Ekle");
        btnOkulEkle.setEnabled(false);
        btnOkulEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkulEkleActionPerformed(evt);
            }
        });

        btnOkulSil.setBackground(new java.awt.Color(153, 153, 153));
        btnOkulSil.setText("Okul Sil");
        btnOkulSil.setEnabled(false);
        btnOkulSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkulSilActionPerformed(evt);
            }
        });

        btnOkulDuzenle.setBackground(new java.awt.Color(153, 153, 153));
        btnOkulDuzenle.setText("Okul Düzenle");
        btnOkulDuzenle.setEnabled(false);
        btnOkulDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkulDuzenleActionPerformed(evt);
            }
        });

        lblMesaj.setText("jLabel4");

        btnTemizle.setBackground(new java.awt.Color(204, 204, 204));
        btnTemizle.setText("vazgeç");
        btnTemizle.setEnabled(false);
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        lblArama.setText("Arama:");

        txtArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAramaKeyReleased(evt);
            }
        });

        jLabel4.setText("Okul Bitiş Saati");

        txtBitisSaati.setEnabled(false);

        btnYeni.setBackground(new java.awt.Color(204, 204, 204));
        btnYeni.setText("Yeni");
        btnYeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMesaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(lblArama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtArama, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtOkulAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBitisSaati, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnYeni)
                .addGap(18, 18, 18)
                .addComponent(btnOkulEkle)
                .addGap(18, 18, 18)
                .addComponent(btnTemizle)
                .addGap(32, 32, 32)
                .addComponent(btnOkulDuzenle)
                .addGap(18, 18, 18)
                .addComponent(btnOkulSil)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOkulAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBitisSaati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArama))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkulEkle)
                    .addComponent(btnTemizle)
                    .addComponent(btnOkulDuzenle)
                    .addComponent(btnOkulSil)
                    .addComponent(btnYeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(lblMesaj))
        );

        okulTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Okul adı:", "Adres", "Baslama Saati", "Bitiş Saati:"
            }
        ));
        okulTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okulTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(okulTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void durumKontrol(boolean durum){
txtBitisSaati.setEnabled(durum);
txtOkulAdi.setEnabled(durum);
txtOkulAdres.setEnabled(durum);
txtSaat.setEnabled(durum);
btnYeni.setEnabled(durum);
btnTemizle.setEnabled(!durum);
btnOkulEkle.setEnabled(!durum);
btnOkulDuzenle.setEnabled(durum);
btnOkulSil.setEnabled(durum);
okulTable.setEnabled(durum);

}

    private void btnOkulEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkulEkleActionPerformed
       String ad=txtOkulAdi.getText();
       Time BaslamaSaati=Time.valueOf(txtSaat.getText());
       Time BitisSaati=Time.valueOf(txtBitisSaati.getText());
       String adres=txtOkulAdres.getText();
       
       islemler.okulEkle(ad, BaslamaSaati, adres,BitisSaati);
       okulGoruntule();
    }//GEN-LAST:event_btnOkulEkleActionPerformed

    private void btnOkulDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkulDuzenleActionPerformed
         String ad=txtOkulAdi.getText();
       Time BaslamaSaati=Time.valueOf(txtSaat.getText());
       String adres=txtOkulAdres.getText();
              Time BitisSaati=Time.valueOf(txtBitisSaati.getText());

        int secilen_satir=okulTable.getSelectedRow();
         if(secilen_satir==-1){
            if(model.getRowCount()==0){
               lblMesaj.setText("müşteri tablosu boş...");
             
             } 
             else{   lblMesaj.setText(" güncellemek için bir  müşteri seçiniz..");}
            }
         else{
             int id=(int)model.getValueAt(secilen_satir,0);
             islemler.okulGuncelle(id,ad,BaslamaSaati,BitisSaati,adres);  
             okulGoruntule();
            lblMesaj.setText(" müşteri güncellendi");
         
         }
    }//GEN-LAST:event_btnOkulDuzenleActionPerformed

    private void okulTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okulTableMouseClicked
         int secilen_satir=okulTable.getSelectedRow();
       txtOkulAdi.setText(model.getValueAt(secilen_satir, 1).toString());
       txtSaat.setText(model.getValueAt(secilen_satir, 3).toString());
       txtOkulAdres.setText(model.getValueAt(secilen_satir, 2).toString());
       txtBitisSaati.setText(model.getValueAt(secilen_satir, 4).toString());
       btnOkulSil.setEnabled(true);
       btnOkulDuzenle.setEnabled(true);

       
    }//GEN-LAST:event_okulTableMouseClicked
  public void temizle(){
      txtOkulAdi.setText("");
   txtOkulAdres.setText("");
   txtSaat.setText(""); 
   txtBitisSaati.setText("");
  
  
  }
    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
     durumKontrol(true);
     temizle();
         
    }//GEN-LAST:event_btnTemizleActionPerformed

    private void btnOkulSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkulSilActionPerformed
        int secilen_satir=okulTable.getSelectedRow();
         if(secilen_satir==-1){
             if(model.getRowCount()==0){
               lblMesaj.setText("müşteri tablosu boş...");
             
             } 
             else{   lblMesaj.setText(" güncellemek için bir  müşteri seçiniz..");}
            }
         else{   
             int id=(int)model.getValueAt(secilen_satir,0);
             islemler.okulSil(id);  
             okulGoruntule();
             lblMesaj.setText(" müşteri güncellendi");
    }//GEN-LAST:event_btnOkulSilActionPerformed
    }
         
public void Arama(String arama) {
        TableRowSorter<DefaultTableModel> ara = new TableRowSorter<>(model);
        okulTable.setRowSorter(ara);
        ara.setRowFilter(RowFilter.regexFilter(arama));
    }
     
    private void txtAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAramaKeyReleased
        String arama = txtArama.getText();
        Arama(arama);
    }//GEN-LAST:event_txtAramaKeyReleased

    private void btnYeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniActionPerformed
       durumKontrol(false);
    }//GEN-LAST:event_btnYeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OkulEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OkulEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OkulEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OkulEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OkulEkran dialog = new OkulEkran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkulDuzenle;
    private javax.swing.JButton btnOkulEkle;
    private javax.swing.JButton btnOkulSil;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JButton btnYeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArama;
    private javax.swing.JLabel lblMesaj;
    private javax.swing.JTable okulTable;
    private javax.swing.JTextField txtArama;
    private javax.swing.JTextField txtBitisSaati;
    private javax.swing.JTextField txtOkulAdi;
    private javax.swing.JTextArea txtOkulAdres;
    private javax.swing.JTextField txtSaat;
    // End of variables declaration//GEN-END:variables
}
